# Generated by Django 2.0.3 on 2018-08-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=150, verbose_name='编号')),
                ('time', models.CharField(max_length=150, verbose_name='时间')),
                ('location', models.CharField(max_length=150, verbose_name='树莓派')),
                ('color', models.CharField(default='', max_length=50, verbose_name='颜色')),
                ('kind', models.CharField(default='', max_length=50, verbose_name='类型细化')),
            ],
        ),
        migrations.CreateModel(
            name='Sum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0, verbose_name='车总数')),
                ('car1', models.IntegerField(default=0, verbose_name='车型1')),
                ('car2', models.IntegerField(default=0, verbose_name='车型2')),
                ('car3', models.IntegerField(default=0, verbose_name='车型3')),
                ('car4', models.IntegerField(default=0, verbose_name='车型4')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=150, verbose_name='编号')),
                ('time', models.CharField(max_length=150, verbose_name='时间')),
                ('location', models.CharField(max_length=150, verbose_name='树莓派')),
                ('color', models.CharField(default='', max_length=50, verbose_name='颜色')),
                ('kind', models.CharField(default='', max_length=50, verbose_name='类型细化')),
            ],
        ),
    ]
