# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='village',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('x', models.CharField(max_length=50, verbose_name='x')),
                ('y', models.CharField(max_length=50, verbose_name='y')),
            ],
        ),
    ]
